/**
 * ARCHIVED MOCK DATA - DO NOT USE IN PRODUCTION
 *
 * This file contains mock attendee data that was previously used for the stream details page.
 * It is kept for reference and potential future testing purposes.
 */

export interface AttendeeData {
  id: string;
  name: string;
  email: string;
  avatar?: string;
  passName: string;
  passCount?: number;
  status: 'attended' | 'missed';
}

export const MOCK_ATTENDEES: Record<string, AttendeeData[]> = {
  // Completed streams - have attended/missed status mix
  vc_completed_1: [
    {
      id: 'att_1',
      name: 'John Doe',
      email: 'john.doe@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_2',
      name: 'Jane Smith',
      email: 'jane.smith@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_3',
      name: 'Bob Wilson',
      email: 'bob.wilson@example.com',
      passName: 'Premium Pass',
      status: 'missed',
    },
    {
      id: 'att_4',
      name: 'Alice Johnson',
      email: 'alice.j@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_5',
      name: 'Charlie Brown',
      email: 'charlie.b@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_6',
      name: 'Diana Ross',
      email: 'diana.r@example.com',
      passName: 'Free Pass',
      status: 'missed',
    },
    {
      id: 'att_7',
      name: 'Edward Kim',
      email: 'edward.kim@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_8',
      name: 'Fiona Garcia',
      email: 'fiona.g@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_9',
      name: 'George Miller',
      email: 'george.m@example.com',
      passName: 'Premium Pass',
      status: 'missed',
    },
    {
      id: 'att_10',
      name: 'Hannah Lee',
      email: 'hannah.lee@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
  ],
  vc_completed_2: [
    {
      id: 'att_11',
      name: 'Ian Thompson',
      email: 'ian.t@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_12',
      name: 'Julia Martinez',
      email: 'julia.m@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_13',
      name: 'Kevin Chen',
      email: 'kevin.c@example.com',
      passName: 'Premium Pass',
      status: 'missed',
    },
    {
      id: 'att_14',
      name: 'Laura Davis',
      email: 'laura.d@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_15',
      name: 'Michael Park',
      email: 'michael.p@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_16',
      name: 'Nina Patel',
      email: 'nina.p@example.com',
      passName: 'Free Pass',
      status: 'missed',
    },
    {
      id: 'att_17',
      name: 'Oscar White',
      email: 'oscar.w@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_18',
      name: 'Patricia Adams',
      email: 'patricia.a@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
  ],
  vc_completed_3: [
    {
      id: 'att_19',
      name: 'Quinn Taylor',
      email: 'quinn.t@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_20',
      name: 'Rachel Green',
      email: 'rachel.g@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_21',
      name: 'Samuel Lewis',
      email: 'samuel.l@example.com',
      passName: 'Premium Pass',
      status: 'missed',
    },
    {
      id: 'att_22',
      name: 'Tina Walker',
      email: 'tina.w@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_23',
      name: 'Uma Sharma',
      email: 'uma.s@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_24',
      name: 'Victor Hall',
      email: 'victor.h@example.com',
      passName: 'Free Pass',
      status: 'missed',
    },
  ],

  // Live streams - all 'attended' (currently watching)
  vc_live_1: [
    {
      id: 'att_25',
      name: 'Wendy Clark',
      email: 'wendy.c@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_26',
      name: 'Xavier Jones',
      email: 'xavier.j@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_27',
      name: 'Yvonne King',
      email: 'yvonne.k@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_28',
      name: 'Zachary Brown',
      email: 'zachary.b@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_29',
      name: 'Amy Wilson',
      email: 'amy.w@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_30',
      name: 'Brian Scott',
      email: 'brian.s@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_31',
      name: 'Cathy Moore',
      email: 'cathy.m@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_32',
      name: 'Daniel Evans',
      email: 'daniel.e@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
  ],
  vc_live_2: [
    {
      id: 'att_33',
      name: 'Emma Roberts',
      email: 'emma.r@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_34',
      name: 'Frank Turner',
      email: 'frank.t@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_35',
      name: 'Grace Phillips',
      email: 'grace.p@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_36',
      name: 'Henry Campbell',
      email: 'henry.c@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_37',
      name: 'Irene Mitchell',
      email: 'irene.m@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
  ],

  // Live soon streams - all 'attended' (registered/waiting)
  vc_soon_1: [
    {
      id: 'att_38',
      name: 'Jack Robinson',
      email: 'jack.r@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_39',
      name: 'Karen Anderson',
      email: 'karen.a@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_40',
      name: 'Leo Thomas',
      email: 'leo.t@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_41',
      name: 'Maria Jackson',
      email: 'maria.j@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_42',
      name: 'Nick Harris',
      email: 'nick.h@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_43',
      name: 'Olivia Martin',
      email: 'olivia.m@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_44',
      name: 'Peter Thompson',
      email: 'peter.t@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_45',
      name: 'Quinn Garcia',
      email: 'quinn.g@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_46',
      name: 'Ruby Martinez',
      email: 'ruby.m@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
  ],
  vc_soon_2: [
    {
      id: 'att_47',
      name: 'Steve Rodriguez',
      email: 'steve.r@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_48',
      name: 'Tracy Wilson',
      email: 'tracy.w@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_49',
      name: 'Ursula Moore',
      email: 'ursula.m@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_50',
      name: 'Vincent Taylor',
      email: 'vincent.t@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_51',
      name: 'Wanda Anderson',
      email: 'wanda.a@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_52',
      name: 'Xavier Thomas',
      email: 'xavier.t@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
  ],

  // Upcoming streams - all 'attended' (registered)
  vc_upcoming_1: [
    {
      id: 'att_53',
      name: 'Yolanda Jackson',
      email: 'yolanda.j@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_54',
      name: 'Zane Harris',
      email: 'zane.h@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_55',
      name: 'Abigail Martin',
      email: 'abigail.m@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_56',
      name: 'Benjamin Thompson',
      email: 'benjamin.t@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_57',
      name: 'Charlotte Garcia',
      email: 'charlotte.g@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_58',
      name: 'Dylan Martinez',
      email: 'dylan.m@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_59',
      name: 'Eleanor Rodriguez',
      email: 'eleanor.r@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_60',
      name: 'Felix Wilson',
      email: 'felix.w@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_61',
      name: 'Gabriella Moore',
      email: 'gabriella.m@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_62',
      name: 'Harrison Taylor',
      email: 'harrison.t@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_63',
      name: 'Isabella Anderson',
      email: 'isabella.a@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_64',
      name: 'Jonathan Thomas',
      email: 'jonathan.t@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
  ],
  vc_upcoming_2: [
    {
      id: 'att_65',
      name: 'Katherine Jackson',
      email: 'katherine.j@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_66',
      name: 'Liam Harris',
      email: 'liam.h@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_67',
      name: 'Madison Martin',
      email: 'madison.m@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_68',
      name: 'Nathan Thompson',
      email: 'nathan.t@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_69',
      name: 'Olivia Garcia',
      email: 'olivia.g@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_70',
      name: 'Patrick Martinez',
      email: 'patrick.m@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_71',
      name: 'Queenie Rodriguez',
      email: 'queenie.r@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_72',
      name: 'Ryan Wilson',
      email: 'ryan.w@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
  ],
  vc_upcoming_3: [
    {
      id: 'att_73',
      name: 'Sophia Moore',
      email: 'sophia.m@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_74',
      name: 'Tyler Taylor',
      email: 'tyler.t@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_75',
      name: 'Ursula Anderson',
      email: 'ursula.a@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_76',
      name: 'Vincent Thomas',
      email: 'vincent.t2@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_77',
      name: 'Willow Jackson',
      email: 'willow.j@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_78',
      name: 'Xavier Harris',
      email: 'xavier.h@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_79',
      name: 'Yasmine Martin',
      email: 'yasmine.m@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
  ],
  vc_upcoming_4: [
    {
      id: 'att_80',
      name: 'Zachary Thompson',
      email: 'zachary.t@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_81',
      name: 'Aria Garcia',
      email: 'aria.g@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_82',
      name: 'Blake Martinez',
      email: 'blake.m@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_83',
      name: 'Cora Rodriguez',
      email: 'cora.r@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_84',
      name: 'Drake Wilson',
      email: 'drake.w@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_85',
      name: 'Eva Moore',
      email: 'eva.m@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_86',
      name: 'Finn Taylor',
      email: 'finn.t@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
    {
      id: 'att_87',
      name: 'Gemma Anderson',
      email: 'gemma.a@example.com',
      passName: 'Free Pass',
      status: 'attended',
    },
    {
      id: 'att_88',
      name: 'Hugo Thomas',
      email: 'hugo.t@example.com',
      passName: 'Premium Pass',
      status: 'attended',
    },
  ],
};
